export const userPaths = {
  root: '/',
  top: '/top',
  registerVerifyEmail: '/register/verify-email',
  register: '/register',
  resetPasswordVerifyEmail: '/reset-password/verify-email',
  resetPassword: '/reset-password',
  login: '/login',
  account: '/account-information',
  consentConfirmationForm: '/consent-confirmation-form',
  unsubcribed: '/unsubcribed',
  updatePassword: '/update-password',
  changeEmailVerifyEmail: '/change-email/verify-email',
  changeEmail: '/change-email',
  spStep0: '/step-0',
  spStep1: '/step-1',
  spStep2: '/step-2',
  spStep3: '/step-3',
  spStep4: '/step-4',
  spStep5: '/step-5',
  spStep6: '/step-6',
  spStep7: '/step-7',
  spStep8: '/step-8',
  spStep9: '/step-9',
  spStep10: '/step-10',
  spStep11: '/step-11',
  spStep12: '/step-12',
  spStep13: '/step-13',
  spStep14: '/step-14',

  //
  spTermOfServiceUrl: '/pdfs/利用規約.pdf',
  spConfirmationUrl: '/pdfs/銀行代理業にかかる確認書.pdf',
  spConsentUrl: '/pdfs/個人情報の取扱いに関する同意書兼表明および確約書.pdf',
};
