export const typography = {
  note: {
    fontFamily: 'Hiragino Sans',
    fontSize: 12,
    fontWeight: 300,
    lineHeight: '150%',
    fontStyle: 'normal',
    letterSpacing: 0.6,
    whiteSpace: 'break-spaces',
  },
  step_label: {
    fontFamily: 'Hiragino Sans',
    fontSize: 12,
    fontWeight: 500,
    lineHeight: '120%',
    fontStyle: 'normal',
    letterSpacing: 0.6,
    whiteSpace: 'break-spaces',
  },
  help: {
    fontFamily: 'Hiragino Sans',
    fontSize: 12,
    fontWeight: 500,
    lineHeight: '100%',
    fontStyle: 'normal',
    letterSpacing: 0.6,
    textDecorationLine: 'underline',
  },
  waring: {
    fontFamily: 'Hiragino Sans',
    fontSize: 12,
    fontWeight: 500,
    lineHeight: '130%',
    fontStyle: 'normal',
    letterSpacing: 0.6,
    whiteSpace: 'break-spaces',
  },
  page_title: {
    fontFamily: 'Hiragino Sans',
    fontSize: 24,
    fontWeight: 500,
    lineHeight: '150%',
    fontStyle: 'normal',
    letterSpacing: 0.6,
    whiteSpace: 'break-spaces',
    textAlign: 'center',
  },
  modal_title: {
    fontFamily: 'Hiragino Sans',
    fontSize: 20,
    fontWeight: 500,
    lineHeight: '130%',
    fontStyle: 'normal',
    letterSpacing: 0.6,
    whiteSpace: 'break-spaces',
    textAlign: 'center',
  },
  modal_label: {
    fontFamily: 'Hiragino Sans',
    fontSize: 16,
    fontWeight: 300,
    lineHeight: '170%',
    fontStyle: 'normal',
    letterSpacing: 0.6,
    whiteSpace: 'break-spaces',
    textAlign: 'center',
  },
  chip_label: {
    fontFamily: 'Hiragino Sans',
    fontSize: 10,
    fontWeight: 500,
    lineHeight: '100%',
    fontStyle: 'normal',
    letterSpacing: 0.6,
  },
  form_item_label: {
    fontFamily: 'Hiragino Sans',
    fontSize: 16,
    fontWeight: 500,
    lineHeight: '130%',
    fontStyle: 'normal',
    letterSpacing: 0.6,
  },
  radio_checkbox_button: {
    fontFamily: 'Hiragino Sans',
    fontSize: 16,
    fontWeight: 500,
    lineHeight: '130%',
    fontStyle: 'normal',
    letterSpacing: 0.6,
  },
  label: {
    fontFamily: 'Hiragino Sans',
    fontSize: 14,
    fontWeight: 500,
    lineHeight: '100%',
    fontStyle: 'normal',
    letterSpacing: 0.6,
  },
  notify: {
    fontFamily: 'Hiragino Sans',
    fontSize: 14,
    fontWeight: 300,
    lineHeight: '170%',
    fontStyle: 'normal',
    letterSpacing: 0.6,
    whiteSpace: 'break-spaces',
  },
  step: {
    fontFamily: 'Barlow',
    fontStyle: 'normal',
    fontWeight: 500,
    fontSize: 14,
    lineHeight: '100%',
    letterSpacing: 0.6,
  },
  unit: {
    fontFamily: 'Hiragino Sans',
    fontStyle: 'normal',
    fontSize: 16,
    fontWeight: 300,
    lineHeight: '100%',
    letterSpacing: 0.6,
  },
  chat_new_message: {
    fontFamily: 'Noto Sans JP',
    fontWeight: 700,
    fontSize: 12,
    lineHeight: '12px',
    letterSpacing: 0.6,
  },
  chat_message: {
    fontFamily: 'Hiragino Sans',
    fontWeight: 300,
    fontSize: 14,
    lineHeight: '170%',
    letterSpacing: 0.6,
    whiteSpace: 'break-spaces',
    wordBreak: 'break-all',
  },
  chat_title: {
    fontFamily: 'Hiragino Sans',
    fontWeight: 300,
    fontSize: 12,
    lineHeight: '100%',
    letterSpacing: 0.6,
  },
};
