export const typography = {
  login_title: {
    fontFamily: 'Hiragino Sans',
    fontWeight: 600,
    fontSize: 18,
    lineHeight: '27px',
    letterSpacing: 0.05,
  },
  login_input: {
    fontFamily: 'Hiragino Sans',
    fontWeight: 600,
    fontSize: 14,
    lineHeight: '21px',
  },
  login_button: {
    fontFamily: 'Hiragino Sans',
    fontWeight: 600,
    fontSize: 12,
    lineHeight: '18px',
    letterSpacing: 0.05,
  },
  login_footer: {
    fontFamily: 'Hiragino Sans',
    fontSize: 12,
    fontWeight: 300,
    lineHeight: '16.8px',
  },
  login_footer_link: {
    fontFamily: 'Hiragino Sans',
    fontSize: 12,
    lineHeight: '18px',
    fontWeight: 600,
    cursor: 'pointer',
  },
  login_valid_error: {
    fontFamily: 'Hiragino Sans',
    fontSize: '12px',
    fontWeight: 500,
    lineHeight: '130%',
    letterSpacing: '0.6px',
    color: '#E54E75',
  },
  login_error: {
    fontFamily: 'Hiragino Sans',
    fontSize: '13px',
    fontWeight: '500',
    lineHeight: '100%',
    letterSpacing: '0.6px',
    color: '#E54E75',
  },
  annotation_01: {
    fontFamily: 'Hiragino Sans',
    fontWeight: 300,
    fontSize: 12,
    lineHeight: '18px',
    textAlign: 'center',
  },

  annotation_02: {
    fontFamily: 'Hiragino Sans',
    fontWeight: 250,
    fontSize: 14,
    lineHeight: '21px',
    textAlign: 'center',
  },
  reset_pwd_note: {
    fontFamily: 'Hiragino Sans',
    fontSize: 12,
    fontWeight: 300,
    lineHeight: '12px',
    letterSpacing: 0.6,
  },

  main_page_title: {
    fontFamily: 'Hiragino Sans',
    fontSize: 16,
    fontWeight: 500,
    lineHeight: '24px',
    letterSpacing: 1,
    textAlign: 'center',
  },
  main_page_auth_info: {
    fontFamily: 'Noto Sans JP',
    fontSize: '12px',
    fontWeight: 400,
    lineHeight: '12px',
    letterSpacing: '0.6px',
    color: '#333333',
  },
  filter_label: {
    fontFamily: 'Hiragino Sans',
    fontSize: '12px',
    fontWeight: '300',
    lineHeight: '16.8px',
    whiteSpace: 'nowrap',
    color: '#333333',
  },
  setting_popover: {
    fontFamily: 'Hiragino Sans',
    fontStyle: 'normal',
    fontWeight: 300,
    fontSize: 14,
    lineHeight: '24px',
    letterSpacing: 0.1,
    whiteSpace: 'break-spaces',
    wordBreak: 'break-all',
  },
  case_content_title: {
    fontFamily: 'Barlow',
    fontStyle: 'normal',
    fontWeight: 400,
    fontSize: '17px',
    lineHeight: '21px',
    letterSpacing: '1px',
    color: '#333333',
  },
  case_content_text: {
    fontFamily: 'Noto Sans JP',
    fontStyle: 'normal',
    fontWeight: 400,
    fontSize: 15,
    lineHeight: '18.59px',
  },
  case_content_text_edit: {
    fontFamily: 'Hiragino Sans',
    fontStyle: 'normal',
    fontWeight: 400,
    fontSize: 12,
    lineHeight: '20px',
  },
  case_select_text: {
    height: 19,
    fontSize: '13px',
    fontFamily: 'Noto Sans JP',
    fontWeight: 400,
    lineHeight: '19px',
    whiteSpace: 'break-spaces',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    fontStyle: 'normal',
    letterSpacing: 0.4,
  },

  manager_progress_item: {
    fontFamily: 'Hiragino Sans',
    fontStyle: 'normal',
    fontWeight: 300,
    fontSize: 15,
    lineHeight: '24px',
    letterSpacing: 0.5,
  },
  manager_progress_item_title: {
    fontFamily: 'Hiragino Sans',
    fontSize: 8,
    fontWeight: 400,
    lineHeight: '24px',
    letterSpacing: 1,
    color: '#666666',
  },
  edit_header_tools: {
    fontFamily: 'Hiragino Sans',
    fontStyle: 'normal',
    fontWeight: 300,
    fontSize: '13px',
    lineHeight: '19.5px',
  },
  applicant_name: {
    fontFamily: 'Hiragino Sans',
    fontWeight: 500,
    fontSize: '13px',
    lineHeight: '24px',
    letterSpacing: '0.1px',
  },
  edit_content_title: {
    fontFamily: 'Hiragino Sans',
    fontSize: '12px',
    lineHeight: '24px',
    letterSpacing: '1px',
  },
  edit_content: {
    fontFamily: 'Hiragino Sans',
    fontSize: '12px',
    fontWeight: 300,
    lineHeight: '14px',
    color: '#333333',
  },
  edit_notice_icon: {
    fontFamily: 'Hiragino Sans',
    fontStyle: 'normal',
    fontWeight: 600,
    fontSize: 20,
    lineHeight: '28px',
    letterSpacing: 0.2,
    color: '#000000',
    overflow: 'hidden',
    whiteSpace: 'break-spaces',
    wordBreak: 'break-all',
  },
  edit_month: {
    fontFamily: 'Roboto',
    fontWeight: 500,
    fontSize: '12px',
    lineHeight: '150%',
    color: '#333333',
  },
  select_options: {
    fontFamily: 'Hiragino Sans',
    fontWeight: 500,
    fontSize: '10px',
    lineHeight: '15px',
  },
  ad_modal_title: {
    fontFamily: 'Hiragino Sans',
    fontSize: '16px',
    fontWeight: 500,
    height: '24px',
    letterSpacing: '0.15px',
    lineHeight: '24px',
    color: '#333333',
  },
  filter_clear_button: {
    fontFamily: 'Hiragino Sans',
    fontWeight: 300,
    fontSize: '12px',
    color: '#6B70F0',
    cursor: 'pointer',
  },
  filter_item_label: {
    fontFamily: 'Hiragino Sans',
    fontWeight: 600,
    lineHeight: '24px',
    letterSpacing: '1px',
    color: '#333333',
    fontSize: '14px',
  },
  filter_search_button: {
    fontFamily: 'Hiragino Sans',
    fontWeight: 600,
    fontSize: '12px',
    lineHeight: '18px',
  },
  filter_drop_down: {
    fontFamily: 'Hiragino Sans',
    letterSpacing: '1px',
    fontSize: '14px',
    fontWeight: 300,
    lineHeight: '20px',
  },
  fliter_select: {
    fontFamily: 'Hiragino Sans',
    fontWeight: 500,
    lineHeight: '27px',
    color: '#333333',
    fontSize: '12px',
  },
  filter_select_render_value: {
    fontFamily: 'Hiragino Sans',
    fontSize: '16px',
    fontWeight: 300,
    lineHeight: '16px',
    letterSpacing: '0.6px',
  },
  filter_select_placeHolder: {
    fontFamily: 'Hiragino Sans',
    fontSize: '10px',
    lineHeight: '15px',
    color: '#BBBBBB',
  },
  docs_category: {
    fontFamily: 'Barlow',
    fontWeight: 500,
    fontSize: '24px',
    lineHeight: '36px',
    letterSpacing: '5px',
    color: '#6B70F0',
  },
  docs_category_label: {
    fontFamily: 'Hiragino Sans',
    fontWeight: 500,
    fontSize: '16px',
    lineHeight: '20px',
    letterSpacing: '0.6px',
    color: '#333333',
  },
  docs_subtitle: {
    fontFamily: 'Hiragino Sans',
    fontWeight: 300,
    fontSize: '13px',
    lineHeight: '18px',
    letterSpacing: '0.15px',
    color: '#333333',
  },
  docs_upload_button: {
    fontFamily: 'Hiragino Sans',
    fontWeight: 600,
    fontSize: '12px',
    lineHeight: '18px',
  },
  docs_upload_filename: {
    fontFamily: 'Roboto',
    fontWeight: 400,
    fontSize: '16px',
    lineHeight: '24px',
    color: '#6B70F0',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  docs_upload_error: {
    fontFamily: 'Hiragino Sans',
    fontWeight: 300,
    fontSize: '14px',
    color: '#E54E75',
  },
  title_card_preview: {
    fontFamily: 'Hiragino Sans',
    fontStyle: 'normal',
    fontWeight: 300,
    fontSize: 16,
    lineHeight: '22px',
    letterSpacing: 0.15,
    color: '#333333',
  },
  doc_preview_title: {
    fontFamily: 'Hiragino Sans',
    fontWeight: 400,
    fontSize: 16,
    lineHeight: 1.5,
    color: '#333333',
  },
  doc_download_button: {
    fontFamily: 'Hiragino Sans',
    fontWeight: 600,
    fontSize: 12,
    lineHeight: '18px',
    letterSpacing: '0.05px',
  },
  doc_download_note_title: {
    fontFamily: 'Hiragino Sans',
    fontWeight: 600,
    fontSize: 14,
    lineHeight: '18px',
    letterSpacing: '0.05px',
    color: '#333333',
  },
  doc_delete_modal_title: {
    fontFamily: 'Hiragino Sans',
    fontWeight: 600,
    fontSize: 16,
    lineHeight: '20px',
    letterSpacing: '0.1px',
    color: '#333333',
    whiteSpace: 'break-spaces',
    wordBreak: 'break-all',
  },
  doc_upload_page_text: {
    fontFamily: 'Hiragino Sans',
    fontWeight: 400,
    fontSize: '14px',
    lineHeight: '21px',
    color: '#333333',
  },
};
